name: Deploy to Azure WebApp

on:
  pull_request: 
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'frontendApp'
  REGISTRY_LOGIN_SERVER: 'smconta.azurecr.io' 
  IMAGE_NAME: 'frontend-app' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Log into ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME_FRONT }}
        password: ${{ secrets.ACR_PASSWORD_FRONT }}

    - name: Construcción y push de la imagen Docker
      run: |
        docker build -f client/Dockerfile -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Desplegar en Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_DEPLOYMENT_FRONT }}
        images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'

 
