name: Frontend - Validación Local (QA)

on:
  push:
    branches:
      - 'Feat_*'
    paths:
      - 'client/**'

  pull_request:
    branches:
      - 'QA'
    paths:
      - 'client/**'

  workflow_dispatch:

jobs:
  check-frontend:

    runs-on: self-hosted

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        working-directory: ./client
        run: npm install

      - name: Compilar Frontend
        working-directory: ./client
        run: npm run build

      - name: Construir imagen Docker
        run: |
          docker build -t frontend:latest ./client

      - name: Verificar imagen Docker
        run: docker images
